package net.stln.magitech.init;

import java.util.List;

import net.minecraft.core.Holder;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.stln.magitech.Magitech;
import net.stln.magitech.MagitechRegistries;
import net.stln.magitech.item.ThreadboundGenerator;
import net.stln.magitech.item.tool.partitem.PartItem;
import net.stln.magitech.item.tool.toolitem.PartToolGenerator;
import net.stln.magitech.magic.spell.SpellLike;

public class MagitechCreativeTabs {

    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Magitech.MOD_ID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MAGITECH_TAB =
            CREATIVE_MODE_TABS.register(
                    "magitech_tab",
                    () ->
                            CreativeModeTab.builder()
                                    .title(Component.translatable("itemGroup.magitech.magitech"))
                                    .icon(() -> MagitechItems.GLISTENING_LEXICON.toStack())
                                    .displayItems(
                                            (parameters, output) -> {
                                                var registries = parameters.holders();
                                                var spellLookup =
                                                        registries.lookupOrThrow(
                                                                MagitechRegistries.Keys.SPELL);
                                                List<SpellLike> allSpells =
                                                        spellLookup
                                                                .listElements()
                                                                .map(Holder::value)
                                                                .map(spell -> (SpellLike) spell)
                                                                .toList();

                                                output.accept(
                                                        ThreadboundGenerator.generateThreadbound(
                                                                MagitechItems.GLISTENING_LEXICON,
                                                                allSpells));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadbound(
                                                                MagitechItems.THE_FIRE_THAT_THINKS,
                                                                allSpells));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadbound(
                                                                MagitechItems
                                                                        .ARCANE_ENGINEERING_COMPENDIUM,
                                                                allSpells));
                                                output.accept(MagitechItems.AETHER_LIFTER);
                                                output.accept(MagitechItems.FLAMGLIDE_STRIDER);
                                                output.accept(MagitechItems.MANA_RING);
                                                output.accept(MagitechItems.GALEVENT_RING);
                                                output.accept(MagitechItems.CHARGEBIND_RING);
                                                output.accept(MagitechItems.TORSION_RING);
                                                output.accept(MagitechItems.UMBRAL_RING);
                                                output.accept(MagitechItems.DAWN_RING);
                                                output.accept(MagitechItems.FLUXBOUND_RING);
                                                output.accept(MagitechItems.ALCHAEFABRIC);
                                                output.accept(MagitechItems.AEGIS_WEAVE);
                                                output.accept(MagitechItems.FLUORITE);
                                                output.accept(MagitechItems.MANA_CHARGED_FLUORITE);
                                                output.accept(MagitechItems.TOURMALINE);
                                                output.accept(MagitechItems.EMBER_CRYSTAL);
                                                output.accept(MagitechItems.GLACE_CRYSTAL);
                                                output.accept(MagitechItems.SURGE_CRYSTAL);
                                                output.accept(MagitechItems.PHANTOM_CRYSTAL);
                                                output.accept(MagitechItems.TREMOR_CRYSTAL);
                                                output.accept(MagitechItems.MAGIC_CRYSTAL);
                                                output.accept(MagitechItems.FLOW_CRYSTAL);
                                                output.accept(MagitechItems.HOLLOW_CRYSTAL);
                                                output.accept(MagitechItems.AGGREGATED_NOCTIS);
                                                output.accept(MagitechItems.AGGREGATED_LUMINIS);
                                                output.accept(MagitechItems.AGGREGATED_FLUXIA);
                                                output.accept(MagitechItems.CITRINE);
                                                output.accept(MagitechItems.CHROMIUM_INGOT);
                                                output.accept(MagitechItems.REDSTONE_CRYSTAL);
                                                output.accept(
                                                        MagitechItems.POLISHED_REDSTONE_CRYSTAL);
                                                output.accept(MagitechItems.SULFUR);
                                                output.accept(MagitechItems.ENDER_METAL_INGOT);
                                                output.accept(MagitechItems.NETHER_STAR_BRILLIANCE);
                                                output.accept(MagitechItems.RADIANT_STEEL_INGOT);
                                                output.accept(MagitechItems.FRIGIDITE);
                                                output.accept(MagitechItems.POLISHED_FRIGIDITE);
                                                output.accept(MagitechItems.TRANSLUCIUM);
                                                output.accept(MagitechItems.POLISHED_TRANSLUCIUM);
                                                output.accept(MagitechItems.RESONITE);
                                                output.accept(MagitechItems.POLISHED_RESONITE);
                                                output.accept(MagitechItems.ABYSSITE);
                                                output.accept(MagitechItems.POLISHED_ABYSSITE);
                                                output.accept(MagitechItems.MANA_DEEXCITER_CORE);
                                                output.accept(MagitechItems.ASPECT_COLLECTOR);
                                                output.accept(MagitechItems.BOOTS_FRAME);
                                                output.accept(MagitechItems.MANA_BERRIES);
                                                output.accept(MagitechItems.MANA_PIE);
                                                output.accept(MagitechItems.WEAVER_SPAWN_EGG);
                                            })
                                    .build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MAGITECH_BLOCK_TAB =
            CREATIVE_MODE_TABS.register(
                    "magitech_block_tab",
                    () ->
                            CreativeModeTab.builder()
                                    .title(
                                            Component.translatable(
                                                    "itemGroup.magitech.magitech_block"))
                                    .icon(() -> MagitechBlocks.ALCHECRYSITE_ITEM.toStack())
                                    .withTabsBefore(MAGITECH_TAB.getKey())
                                    .displayItems(
                                            (parameters, output) -> {
                                                output.accept(
                                                        MagitechBlocks.ENGINEERING_WORKBENCH_ITEM);
                                                output.accept(
                                                        MagitechBlocks.ASSEMBLY_WORKBENCH_ITEM);
                                                output.accept(
                                                        MagitechBlocks.REPAIRING_WORKBENCH_ITEM);
                                                output.accept(
                                                        MagitechBlocks.UPGRADE_WORKBENCH_ITEM);
                                                output.accept(MagitechBlocks.ZARDIUS_CRUCIBLE_ITEM);
                                                output.accept(
                                                        MagitechBlocks.ALCHEMETRIC_PYLON_ITEM);
                                                output.accept(MagitechBlocks.ATHANOR_PILLAR_ITEM);
                                                output.accept(MagitechBlocks.MANA_NODE_ITEM);
                                                output.accept(MagitechBlocks.MANA_VESSEL_ITEM);
                                                output.accept(MagitechBlocks.FLUORITE_ORE_ITEM);
                                                output.accept(
                                                        MagitechBlocks.DEEPSLATE_FLUORITE_ORE_ITEM);
                                                output.accept(MagitechBlocks.TOURMALINE_ORE_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .DEEPSLATE_TOURMALINE_ORE_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .FLUORITE_CRYSTAL_CLUSTER_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .REDSTONE_CRYSTAL_CLUSTER_ITEM);
                                                output.accept(
                                                        MagitechBlocks.SULFUR_CRYSTAL_CLUSTER_ITEM);
                                                output.accept(MagitechBlocks.SULFUR_BLOCK_ITEM);
                                                output.accept(MagitechBlocks.MISTALIA_PETALS_ITEM);
                                                output.accept(MagitechBlocks.ALCHECRYSITE_ITEM);
                                                output.accept(
                                                        MagitechBlocks.ALCHECRYSITE_STAIRS_ITEM);
                                                output.accept(
                                                        MagitechBlocks.ALCHECRYSITE_SLAB_ITEM);
                                                output.accept(
                                                        MagitechBlocks.ALCHECRYSITE_WALL_ITEM);
                                                output.accept(
                                                        MagitechBlocks.POLISHED_ALCHECRYSITE_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .POLISHED_ALCHECRYSITE_STAIRS_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .POLISHED_ALCHECRYSITE_SLAB_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .POLISHED_ALCHECRYSITE_WALL_ITEM);
                                                output.accept(
                                                        MagitechBlocks.ALCHECRYSITE_BRICKS_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .ALCHECRYSITE_BRICK_STAIRS_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .ALCHECRYSITE_BRICK_SLAB_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .ALCHECRYSITE_BRICK_WALL_ITEM);
                                                output.accept(
                                                        MagitechBlocks.ALCHECRYSITE_TILES_ITEM);
                                                output.accept(MagitechBlocks.FLUORITE_BLOCK_ITEM);
                                                output.accept(MagitechBlocks.FLUORITE_BRICKS_ITEM);
                                                output.accept(
                                                        MagitechBlocks.FLUORITE_BRICK_STAIRS_ITEM);
                                                output.accept(
                                                        MagitechBlocks.FLUORITE_BRICK_SLAB_ITEM);
                                                output.accept(
                                                        MagitechBlocks.FLUORITE_BRICK_WALL_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_LOG_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_WOOD_ITEM);
                                                output.accept(
                                                        MagitechBlocks.STRIPPED_CELIFERN_LOG_ITEM);
                                                output.accept(
                                                        MagitechBlocks.STRIPPED_CELIFERN_WOOD_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_PLANKS_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_STAIRS_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_SLAB_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_FENCE_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CELIFERN_FENCE_GATE_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_DOOR_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CELIFERN_TRAPDOOR_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .CELIFERN_PRESSURE_PLATE_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_BUTTON_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_LEAVES_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_SAPLING_ITEM);
                                                output.accept(MagitechBlocks.CELIFERN_SIGN_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CELIFERN_HANGING_SIGN_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_LOG_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_WOOD_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .STRIPPED_CHARCOAL_BIRCH_LOG_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .STRIPPED_CHARCOAL_BIRCH_WOOD_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_PLANKS_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_STAIRS_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_SLAB_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_FENCE_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .CHARCOAL_BIRCH_FENCE_GATE_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_DOOR_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .CHARCOAL_BIRCH_TRAPDOOR_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .CHARCOAL_BIRCH_PRESSURE_PLATE_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_BUTTON_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_LEAVES_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_SAPLING_ITEM);
                                                output.accept(
                                                        MagitechBlocks.CHARCOAL_BIRCH_SIGN_ITEM);
                                                output.accept(
                                                        MagitechBlocks
                                                                .CHARCOAL_BIRCH_HANGING_SIGN_ITEM);
                                                output.accept(
                                                        MagitechBlocks.SCORCHED_GRASS_SOIL_ITEM);
                                                output.accept(MagitechBlocks.SCORCHED_SOIL_ITEM);
                                            })
                                    .build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MAGITECH_TOOL_TAB =
            CREATIVE_MODE_TABS.register(
                    "magitech_tool_tab",
                    () ->
                            CreativeModeTab.builder()
                                    .title(
                                            Component.translatable(
                                                    "itemGroup.magitech.magitech_tool"))
                                    .icon(
                                            () ->
                                                    PartToolGenerator.generateLightSword(
                                                            MagitechToolMaterials.FLUORITE))
                                    .withTabsBefore(MAGITECH_BLOCK_TAB.getKey())
                                    .displayItems(
                                            (parameters, output) -> {
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.WOOD));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.STONE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.DEEPSLATE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.COPPER));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.BONE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.MOSS));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.IRON));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.GOLD));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.AMETHYST));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.CITRINE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.REDSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.LAPIS));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.CALCITE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.DRIPSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.FLUORITE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.DIAMOND));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.EMERALD));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.ENDER_METAL));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.QUARTZ));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.GLOWSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.NETHERITE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials
                                                                        .RADIANT_STEEL));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.FRIGIDITE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.RESONITE));
                                                output.accept(
                                                        PartToolGenerator.generateDagger(
                                                                MagitechToolMaterials.ABYSSITE));

                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.WOOD));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.STONE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.DEEPSLATE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.COPPER));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.BONE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.MOSS));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.IRON));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.GOLD));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.AMETHYST));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.CITRINE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.REDSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.LAPIS));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.CALCITE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.DRIPSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.FLUORITE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.DIAMOND));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.EMERALD));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.ENDER_METAL));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.QUARTZ));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.GLOWSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.NETHERITE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials
                                                                        .RADIANT_STEEL));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.FRIGIDITE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.RESONITE));
                                                output.accept(
                                                        PartToolGenerator.generateLightSword(
                                                                MagitechToolMaterials.ABYSSITE));

                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.WOOD));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.STONE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.DEEPSLATE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.COPPER));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.BONE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.MOSS));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.IRON));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.GOLD));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.AMETHYST));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.CITRINE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.REDSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.LAPIS));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.CALCITE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.DRIPSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.FLUORITE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.DIAMOND));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.EMERALD));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.ENDER_METAL));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.QUARTZ));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.GLOWSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.NETHERITE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials
                                                                        .RADIANT_STEEL));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.FRIGIDITE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.RESONITE));
                                                output.accept(
                                                        PartToolGenerator.generateHeavySword(
                                                                MagitechToolMaterials.ABYSSITE));

                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.WOOD));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.STONE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.DEEPSLATE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.COPPER));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.BONE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.MOSS));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.IRON));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.GOLD));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.AMETHYST));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.CITRINE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.REDSTONE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.LAPIS));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.CALCITE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.DRIPSTONE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.FLUORITE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.DIAMOND));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.EMERALD));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.ENDER_METAL));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.QUARTZ));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.GLOWSTONE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.NETHERITE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials
                                                                        .RADIANT_STEEL));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.FRIGIDITE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.RESONITE));
                                                output.accept(
                                                        PartToolGenerator.generatePickaxe(
                                                                MagitechToolMaterials.ABYSSITE));

                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.WOOD));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.STONE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.DEEPSLATE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.COPPER));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.BONE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.MOSS));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.IRON));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.GOLD));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.AMETHYST));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.CITRINE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.REDSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.LAPIS));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.CALCITE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.DRIPSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.FLUORITE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.DIAMOND));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.EMERALD));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.ENDER_METAL));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.QUARTZ));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.GLOWSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.NETHERITE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials
                                                                        .RADIANT_STEEL));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.FRIGIDITE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.RESONITE));
                                                output.accept(
                                                        PartToolGenerator.generateHammer(
                                                                MagitechToolMaterials.ABYSSITE));

                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.WOOD));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.STONE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.DEEPSLATE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.COPPER));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.BONE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.MOSS));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.IRON));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.GOLD));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.AMETHYST));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.CITRINE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.REDSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.LAPIS));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.CALCITE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.DRIPSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.FLUORITE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.DIAMOND));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.EMERALD));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.ENDER_METAL));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.QUARTZ));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.GLOWSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.NETHERITE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials
                                                                        .RADIANT_STEEL));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.FRIGIDITE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.RESONITE));
                                                output.accept(
                                                        PartToolGenerator.generateAxe(
                                                                MagitechToolMaterials.ABYSSITE));

                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.WOOD));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.STONE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.DEEPSLATE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.COPPER));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.BONE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.MOSS));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.IRON));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.GOLD));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.AMETHYST));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.CITRINE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.REDSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.LAPIS));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.CALCITE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.DRIPSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.FLUORITE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.DIAMOND));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.EMERALD));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.ENDER_METAL));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.QUARTZ));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.GLOWSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.NETHERITE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials
                                                                        .RADIANT_STEEL));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.FRIGIDITE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.RESONITE));
                                                output.accept(
                                                        PartToolGenerator.generateShovel(
                                                                MagitechToolMaterials.ABYSSITE));

                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.WOOD));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.STONE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.DEEPSLATE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.COPPER));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.BONE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.MOSS));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.IRON));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.GOLD));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.AMETHYST));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.CITRINE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.REDSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.LAPIS));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.CALCITE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.DRIPSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.FLUORITE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.DIAMOND));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.EMERALD));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.ENDER_METAL));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.QUARTZ));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.GLOWSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.NETHERITE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials
                                                                        .RADIANT_STEEL));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.FRIGIDITE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.RESONITE));
                                                output.accept(
                                                        PartToolGenerator.generateScythe(
                                                                MagitechToolMaterials.ABYSSITE));

                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.WOOD));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.STONE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.DEEPSLATE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.COPPER));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.BONE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.MOSS));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.IRON));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.GOLD));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.AMETHYST));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.CITRINE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.REDSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.LAPIS));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.CALCITE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.DRIPSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.FLUORITE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.DIAMOND));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.EMERALD));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.ENDER_METAL));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.QUARTZ));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.GLOWSTONE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.NETHERITE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials
                                                                        .RADIANT_STEEL));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.FRIGIDITE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.TRANSLUCIUM));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.RESONITE));
                                                output.accept(
                                                        PartToolGenerator.generateWand(
                                                                MagitechToolMaterials.ABYSSITE));
                                            })
                                    .build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MAGITECH_PART_TAB =
            CREATIVE_MODE_TABS.register(
                    "magitech_part_tab",
                    () ->
                            CreativeModeTab.builder()
                                    .title(
                                            Component.translatable(
                                                    "itemGroup.magitech.magitech_part"))
                                    .icon(
                                            () ->
                                                    PartToolGenerator.generatePart(
                                                            MagitechItems.LIGHT_BLADE.get(),
                                                            MagitechToolMaterials.FLUORITE))
                                    .withTabsBefore(MAGITECH_TOOL_TAB.getKey())
                                    .displayItems(
                                            (parameters, output) -> {
                                                List<DeferredItem<PartItem>> partList =
                                                        List.of(
                                                                MagitechItems.LIGHT_BLADE,
                                                                MagitechItems.HEAVY_BLADE,
                                                                MagitechItems.LIGHT_HANDLE,
                                                                MagitechItems.HEAVY_HANDLE,
                                                                MagitechItems.TOOL_BINDING,
                                                                MagitechItems.HANDGUARD,
                                                                MagitechItems.STRIKE_HEAD,
                                                                MagitechItems.SPIKE_HEAD,
                                                                MagitechItems.REINFORCED_STICK,
                                                                MagitechItems.PLATE,
                                                                MagitechItems.CATALYST,
                                                                MagitechItems.CONDUCTOR);
                                                for (DeferredItem<PartItem> item : partList) {
                                                    MagitechToolMaterials.REGISTER
                                                            .getMaterials()
                                                            .map(
                                                                    material ->
                                                                            PartToolGenerator
                                                                                    .generatePart(
                                                                                            item
                                                                                                    .get(),
                                                                                            material))
                                                            .forEach(output::accept);
                                                }
                                            })
                                    .build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MAGITECH_SPELL_TAB =
            CREATIVE_MODE_TABS.register(
                    "magitech_spell_tab",
                    () ->
                            CreativeModeTab.builder()
                                    .title(
                                            Component.translatable(
                                                    "itemGroup.magitech.magitech_spell"))
                                    .icon(
                                            () ->
                                                    ThreadboundGenerator.generateThreadPage(
                                                            MagitechSpells.ENERCRUX))
                                    .withTabsBefore(MAGITECH_PART_TAB.getKey())
                                    .displayItems(
                                            (parameters, output) -> {
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.IGNISCA));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.PYROLUX));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.FLUVALEN));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.BLAZEWEND));

                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.FRIGALA));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.CRYOLUXA));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.NIVALUNE));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.GLISTELDA));

                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.VOLTARIS));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.FULGENZA));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.SPARKION));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.ARCLUME));

                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.MIRAZIEN));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.PHANTASTRA));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.VEILMIST));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.FADANCEA));

                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.TREMIVOX));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.OSCILBEAM));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.SONISTORM));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.QUAVERIS));

                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.ARCALETH));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.MYSTAVEN));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.GLYMORA));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.ENVISTRA));

                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.AELTHERIN));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.FLUVINAE));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.MISTRELUNE));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.SYLLAEZE));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.NYMPHORA));

                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.NULLIXIS));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.VOIDLANCE));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.TENEBRISOL));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.DISPARUNDRA));
                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.TENEBPORT));

                                                output.accept(
                                                        ThreadboundGenerator.generateThreadPage(
                                                                MagitechSpells.ENERCRUX));
                                            })
                                    .build());

    public static void registerCreativeTabs(IEventBus eventBus) {
        Magitech.LOGGER.info("Registering Creative Tabs for" + Magitech.MOD_ID);
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
